library(imager)
tiff("./figures/Fig7.tif",compression="lzw",res=600,unit="in",width=7,height=3.5)
par(mfrow=c(1,2))
par(mar = c(0,0,0,0))
im <- load.image("./figures/spatial_patterns_normalized_tirs.tif")
plot(im,axes=FALSE)
mtext(side = 3, line = -1.2, adj = 0.04, 'A', font = 2)
im <- load.image("./figures/spatial_patterns_normalized_tirs_ulv_colorbar.tif")
plot(im,axes=FALSE)
mtext(side = 3, line = -1.2, adj = 0.04, 'B', font = 2)
##par(mar = c(0,0.1,1.3,0.1))
dev.off()
